#!/usr/bin/env ruby
  
require 'optparse'

@assets_path = '/Users/davidconnolly/twg/legacy_data/assets/'

# == Support Methods ========================================================

def sources
  %w[
    sample_source
  ]
end

def import!
  sources.each do |source|
    unless (LegacySource.where(name: source).count > 0)
      file = File.expand_path('raw_data/%s.csv' % source, @assets_path)

      puts "Importing #{file}"

      importer = Importer::GenericCsv.new(file, name: source)

      importer.create_legacy_source!
    end
  end

  sources.each do |source|
    # Run extractor to generate extracted_data
    puts "Extracting Data from source #{source}"

    extractor = Legacy::Extractor.extractor_for(source)

    LegacySource.where(name: source).first.legacy_entities.each do |legacy_entity|
      legacy_entity.extracted_data = extractor.call(legacy_entity)

      legacy_entity.save!
    end
    
    # Filter extracted data
    puts "Generating filter for source #{source}"

    legacy_entities = LegacySource.where(name: source).first.legacy_entities
    filtered_entities = Legacy::Filter::A010101Filter.new(legacy_entities)
     
    # Pass the filtered data to the importer to create the actual record using the extracted data
    puts "Importing Data from source #{source}"

    filtered_entities.each do |entity|
      Legacy::Importer.new(
        entity
      ).import!
    end
  end
end

# == Main ===================================================================

parser = OptionParser.new do |parser|
  parser.banner = "Usage: legacy [command] [options]"

  parser.separator("")
  parser.separator("Commands:")
  parser.separator("")
  parser.separator("    import - Import legacy data")
  parser.separator("")
  parser.separator("Options:")
  parser.separator("")

  parser.on('-a', '--assets=s', 'Specify assets path') do |p|
    @assets_path = File.expand_path(p, Dir.getwd)
  end

  parser.on('-h', '--help') do
    puts parser
    exit(0)
  end
end

args = parser.parse(*ARGV)

if (args.empty?)
  puts parser
  exit(0)
end

args.each do |arg|
  case (arg)
  when 'import'
    import!
  else
    STDERR.puts("Unknown command '#{arg}'")
    exit(-1)
  end
end
